// frontend/src/components/TreeNode.vue
<!-- components/TreeNode.vue -->
<template>
  <div class="tree-node" :style="{ marginLeft: depth * 20 + 'px' }">
    <!-- 节点头部 -->
    <div class="node-header" @click="toggleExpand">
      <!-- 展开/折叠图标 -->
      <div class="expand-icon" v-if="hasChildren">
        <span v-if="isExpanded">▼</span>
        <span v-else>▶</span>
      </div>
      <div v-else class="expand-icon-placeholder"></div>
      
      <!-- 节点内容 -->
      <div class="node-content">
        <div class="question" v-if="node.question">
          <strong>Q:</strong>
          <div class="markdown-wrapper">
            <MarkdownContent :content="node.question" />
          </div>
        </div>
        <div class="answer" v-if="node.answer">
          <strong>A:</strong>
          <div class="markdown-wrapper">
            <MarkdownContent :content="node.answer" />
          </div>
        </div>
      </div>
      
      <!-- 操作按钮 -->
      <div class="node-actions">
        <button 
          class="add-btn" 
          @click.stop="showInput = true;
                      $nextTick(() => {
                        if (inputRef) inputRef.focus();
                      })"
          title="添加子节点"
        >
          +
        </button>
        <button 
          class="delete-btn" 
          @click.stop="deleteNode"
          title="删除节点"
        >
          ×
        </button>
      </div>
    </div>
    
    <!-- 输入框 -->
    <div v-if="showInput" class="input-section">
      <textarea 
        ref="inputRef"
        v-model="newQuestion" 
        placeholder="请输入你的问题..."
        class="input-textarea"
        rows="3"
        @keydown.enter.prevent="sendQuestion"
        @keydown.esc="showInput = false"
      ></textarea>
      <div class="input-actions">
        <button 
          @click="sendQuestion" 
          :disabled="!newQuestion.trim() || loading"
          class="send-btn"
        >
          {{ loading ? '发送中...' : '发送' }}
        </button>
        <button @click="showInput = false" class="cancel-btn" :disabled="loading">
          取消
        </button>
      </div>
    </div>
    
    <!-- 子节点 -->
    <div v-if="isExpanded && hasChildren" class="children">
      <TreeNode 
        v-for="child in node.children" 
        :key="child.id"
        :node="child"
        :depth="depth + 1"
      />
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { useConversationStore } from '@/stores/conversation'
import MarkdownContent from './MarkdownContent.vue'

const props = defineProps({
  node: Object,
  depth: {
    type: Number,
    default: 0
  }
})

const conversationStore = useConversationStore()
const showInput = ref(false)
const newQuestion = ref('')
const loading = ref(false)
const isExpanded = ref(true)
const inputRef = ref(null)

// 判断是否有子节点
const hasChildren = computed(() => {
  return props.node.children && props.node.children.length > 0
})

const toggleExpand = () => {
  if (hasChildren.value) {
    isExpanded.value = !isExpanded.value
  }
}

const sendQuestion = async () => {
  if (!newQuestion.value.trim() || loading.value) return
  
  console.log('[DEBUG] 发送问题:', newQuestion.value)
  loading.value = true
  try {
    await conversationStore.addChildNode(props.node.id, newQuestion.value)
    newQuestion.value = ''
    showInput.value = false
    isExpanded.value = true
    console.log('[DEBUG] 问题发送成功')
  } catch (error) {
    console.error('[ERROR] 发送问题失败:', error)
    alert(`发送问题失败: ${error.message || '未知错误'}`)
  } finally {
    loading.value = false
  }
}

const deleteNode = () => {
  if (confirm('确定要删除这个节点吗？此操作不可撤销。')) {
    console.log('[DEBUG] 删除节点:', props.node.id)
    conversationStore.deleteNode(props.node.id)
  }
}
</script>

<style scoped>
.tree-node {
  margin: 0.5rem 0;
  border: 1px solid #e0e0e0;
  border-radius: 8px;
  overflow: hidden;
  background: white;
  transition: box-shadow 0.2s;
  position: relative;
}

.tree-node:hover {
  box-shadow: 0 2px 8px rgba(0,0,0,0.1);
}

.node-header {
  display: flex;
  align-items: flex-start;
  padding: 0.75rem 1rem;
  background: #f8f9fa;
  cursor: pointer;
  border-bottom: 1px solid #eee;
}

.expand-icon {
  color: #666;
  font-size: 0.8rem;
  margin-right: 0.5rem;
  min-width: 1.5rem;
  text-align: center;
}

.expand-icon-placeholder {
  min-width: 1.5rem;
  margin-right: 0.5rem;
}

.node-content {
  flex: 1;
  margin-right: 0.5rem;
}

.question, .answer {
  margin: 0.25rem 0;
  line-height: 1.5;
  word-wrap: break-word;
  padding: 0.25rem 0;
  display: flex;
  align-items: flex-start;
}

.question strong, .answer strong {
  color: #2c3e50;
  margin-right: 0.5rem;
  display: inline-block;
  min-width: 2rem;
  vertical-align: top;
  flex-shrink: 0;
}

/* 修复 Markdown 内容的对齐问题 */
.markdown-wrapper {
  flex: 1;
  min-width: 0; /* 允许收缩 */
}

.question .markdown-wrapper,
.answer .markdown-wrapper {
  display: block;
}

.node-actions {
  display: flex;
  gap: 0.25rem;
}

.add-btn, .delete-btn {
  padding: 0.25rem 0.5rem;
  border: 1px solid #ddd;
  border-radius: 4px;
  cursor: pointer;
  font-size: 0.9rem;
  transition: all 0.2s;
  width: 28px;
  height: 28px;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 0;
}

.add-btn {
  background: #007bff;
  color: white;
  border-color: #007bff;
}

.add-btn:hover {
  background: #0056b3;
}

.delete-btn {
  background: #dc3545;
  color: white;
  border-color: #dc3545;
}

.delete-btn:hover {
  background: #c82333;
}

.input-section {
  padding: 0.75rem 1rem;
  border-top: 1px solid #eee;
  background: #fafafa;
}

.input-textarea {
  width: 100%;
  padding: 0.5rem;
  border: 1px solid #ddd;
  border-radius: 4px;
  resize: vertical;
  font-family: inherit;
  margin-bottom: 0.5rem;
  font-size: 0.95rem;
}

.input-textarea:focus {
  outline: none;
  border-color: #007bff;
  box-shadow: 0 0 0 2px rgba(0,123,255,0.25);
}

.input-actions {
  display: flex;
  gap: 0.5rem;
  justify-content: flex-end;
}

.send-btn, .cancel-btn {
  padding: 0.25rem 0.5rem;
  border: 1px solid #ddd;
  border-radius: 4px;
  cursor: pointer;
  font-size: 0.9rem;
  transition: all 0.2s;
}

.send-btn {
  background: #28a745;
  color: white;
  border-color: #28a745;
}

.cancel-btn {
  background: #6c757d;
  color: white;
  border-color: #6c757d;
}

.send-btn:hover:not(:disabled), .cancel-btn:hover:not(:disabled) {
  opacity: 0.9;
}

.send-btn:disabled, .cancel-btn:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.children {
  padding-left: 1rem;
  border-left: 2px solid #e0e0e0;
  margin-left: 0.5rem;
}

.children::before {
  content: '';
  position: absolute;
  left: 0.5rem;
  top: 0;
  bottom: 0;
  border-left: 2px solid #e0e0e0;
  pointer-events: none;
}

.tree-node:first-child {
  margin-top: 0;
}

.tree-node:last-child {
  margin-bottom: 0;
}

@media (max-width: 768px) {
  .tree-node {
    margin: 0.25rem 0;
  }
  
  .node-header {
    padding: 0.5rem 0.75rem;
  }
  
  .input-section {
    padding: 0.5rem 0.75rem;
  }
}
</style>

// frontend-react/src/components/TreeNode.js
// src/components/TreeNode.js
import React, { useState, useRef, useCallback } from 'react';
import MarkdownContent from './MarkdownContent';
import { useConversation } from '../stores/conversation'; // Import hook
import './TreeNode.css'; // Import CSS

const TreeNode = ({ node, depth }) => {
  const { addChildNode, deleteNode } = useConversation(); // Use hook
  const [showInput, setShowInput] = useState(false);
  const [newQuestion, setNewQuestion] = useState('');
  const [isExpanded, setIsExpanded] = useState(true);
  const inputRef = useRef(null);

  const hasChildren = node.children && node.children.length > 0;

  const toggleExpand = useCallback(() => {
    if (hasChildren) {
      setIsExpanded(prev => !prev);
    }
  }, [hasChildren]);

  const handleAddClick = useCallback(() => {
    setShowInput(true);
    // Focus after state update
    setTimeout(() => {
      if (inputRef.current) {
        inputRef.current.focus();
      }
    }, 0);
  }, []);

  // 修改 sendQuestion 函数，使其可以从外部调用
  const sendQuestion = useCallback(async () => {
    if (!newQuestion.trim()) return;

    try {
      await addChildNode(node.id, newQuestion);
      setNewQuestion('');
      setShowInput(false);
      setIsExpanded(true); // Expand to show new child
    } catch (error) {
      console.error('[ERROR] 发送问题失败:', error);
      alert(`发送问题失败: ${error.message || '未知错误'}`);
    }
  }, [newQuestion, node.id, addChildNode]);

  const handleDeleteClick = useCallback(() => {
    if (window.confirm('确定要删除这个节点吗？此操作不可撤销。')) {
      console.log('[DEBUG] 删除节点:', node.id);
      deleteNode(node.id);
    }
  }, [node.id, deleteNode]);

  return (
    <div className="tree-node" style={{ marginLeft: `${depth * 20}px` }}>
      <div className="node-header" onClick={toggleExpand}>
        {hasChildren ? (
          <div className="expand-icon" onClick={e => e.stopPropagation()}> {/* Stop propagation on icon click */}
            {isExpanded ? '▼' : '▶'}
          </div>
        ) : (
          <div className="expand-icon-placeholder"></div>
        )}
        <div className="node-content">
          {node.question && (
            <div className="question">
              <strong>Q:</strong>
              <div className="markdown-wrapper">
                <MarkdownContent content={node.question} />
              </div>
            </div>
          )}
          {node.answer && (
            <div className="answer">
              <strong>A:</strong>
              <div className="markdown-wrapper">
                <MarkdownContent content={node.answer} />
              </div>
            </div>
          )}
        </div>
        <div className="node-actions">
          <button
            className="add-btn"
            onClick={handleAddClick}
            title="添加子节点"
          >
            +
          </button>
          <button
            className="delete-btn"
            onClick={handleDeleteClick}
            title="删除节点"
          >
            ×
          </button>
        </div>
      </div>

      {showInput && (
        <div className="input-section">
          <textarea
            ref={inputRef}
            value={newQuestion}
            onChange={(e) => setNewQuestion(e.target.value)}
            placeholder="请输入你的问题..."
            className="input-textarea"
            rows="3"
            // 修改 onKeyDown 逻辑：Enter 换行，Ctrl/Cmd+Enter 发送
            onKeyDown={(e) => {
              if (e.key === 'Enter' && (e.ctrlKey || e.metaKey)) { // 按下 Ctrl+Enter 或 Cmd+Enter (Mac)
                e.preventDefault(); // 防止换行
                sendQuestion(); // 调用发送函数
              }
              if (e.key === 'Escape') {
                setShowInput(false);
              }
            }}
          />
          <div className="input-actions">
            {/* 直接绑定 sendQuestion */}
            <button
              onClick={sendQuestion}
              disabled={!newQuestion.trim()}
              className="send-btn"
            >
              发送
            </button>
            <button
              onClick={() => setShowInput(false)}
              className="cancel-btn"
            >
              取消
            </button>
          </div>
        </div>
      )}

      {isExpanded && hasChildren && (
        <div className="children">
          {node.children.map(child => (
            <TreeNode
              key={child.id}
              node={child}
              depth={depth + 1}
            />
          ))}
        </div>
      )}
    </div>
  );
};

export default TreeNode;
